# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: currencyservice.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='currencyservice.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15\x63urrencyservice.proto\"t\n\x08\x43urrency\x12\x1b\n\x04type\x18\x01 \x01(\x0e\x32\r.CurrencyType\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.Currency.Decimal\x1a)\n\x07\x44\x65\x63imal\x12\x0b\n\x03val\x18\x01 \x01(\r\x12\x11\n\tprecision\x18\x02 \x01(\r\"-\n\rCurrencyTypes\x12\x1c\n\x05types\x18\x01 \x03(\x0e\x32\r.CurrencyType*h\n\x0c\x43urrencyType\x12\x07\n\x03\x45UR\x10\x00\x12\x07\n\x03USD\x10\x01\x12\x07\n\x03GBP\x10\x02\x12\x07\n\x03\x43HF\x10\x03\x12\x07\n\x03SEK\x10\x04\x12\x07\n\x03\x41UD\x10\x05\x12\x07\n\x03\x43\x41\x44\x10\x06\x12\x07\n\x03\x43ZK\x10\x07\x12\x07\n\x03JPY\x10\x08\x12\x07\n\x03RUB\x10\t2A\n\x0f\x43urrencyService\x12.\n\rGetCurrencies\x12\x0e.CurrencyTypes\x1a\t.Currency\"\x00\x30\x01\x62\x06proto3')
)

_CURRENCYTYPE = _descriptor.EnumDescriptor(
  name='CurrencyType',
  full_name='CurrencyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EUR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GBP', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHF', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SEK', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AUD', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CAD', index=6, number=6,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CZK', index=7, number=7,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JPY', index=8, number=8,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUB', index=9, number=9,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=190,
  serialized_end=294,
)
_sym_db.RegisterEnumDescriptor(_CURRENCYTYPE)

CurrencyType = enum_type_wrapper.EnumTypeWrapper(_CURRENCYTYPE)
EUR = 0
USD = 1
GBP = 2
CHF = 3
SEK = 4
AUD = 5
CAD = 6
CZK = 7
JPY = 8
RUB = 9



_CURRENCY_DECIMAL = _descriptor.Descriptor(
  name='Decimal',
  full_name='Currency.Decimal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='Currency.Decimal.val', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='precision', full_name='Currency.Decimal.precision', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=141,
)

_CURRENCY = _descriptor.Descriptor(
  name='Currency',
  full_name='Currency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Currency.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Currency.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CURRENCY_DECIMAL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=141,
)


_CURRENCYTYPES = _descriptor.Descriptor(
  name='CurrencyTypes',
  full_name='CurrencyTypes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='types', full_name='CurrencyTypes.types', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=188,
)

_CURRENCY_DECIMAL.containing_type = _CURRENCY
_CURRENCY.fields_by_name['type'].enum_type = _CURRENCYTYPE
_CURRENCY.fields_by_name['value'].message_type = _CURRENCY_DECIMAL
_CURRENCYTYPES.fields_by_name['types'].enum_type = _CURRENCYTYPE
DESCRIPTOR.message_types_by_name['Currency'] = _CURRENCY
DESCRIPTOR.message_types_by_name['CurrencyTypes'] = _CURRENCYTYPES
DESCRIPTOR.enum_types_by_name['CurrencyType'] = _CURRENCYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Currency = _reflection.GeneratedProtocolMessageType('Currency', (_message.Message,), dict(

  Decimal = _reflection.GeneratedProtocolMessageType('Decimal', (_message.Message,), dict(
    DESCRIPTOR = _CURRENCY_DECIMAL,
    __module__ = 'currencyservice_pb2'
    # @@protoc_insertion_point(class_scope:Currency.Decimal)
    ))
  ,
  DESCRIPTOR = _CURRENCY,
  __module__ = 'currencyservice_pb2'
  # @@protoc_insertion_point(class_scope:Currency)
  ))
_sym_db.RegisterMessage(Currency)
_sym_db.RegisterMessage(Currency.Decimal)

CurrencyTypes = _reflection.GeneratedProtocolMessageType('CurrencyTypes', (_message.Message,), dict(
  DESCRIPTOR = _CURRENCYTYPES,
  __module__ = 'currencyservice_pb2'
  # @@protoc_insertion_point(class_scope:CurrencyTypes)
  ))
_sym_db.RegisterMessage(CurrencyTypes)



_CURRENCYSERVICE = _descriptor.ServiceDescriptor(
  name='CurrencyService',
  full_name='CurrencyService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=296,
  serialized_end=361,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCurrencies',
    full_name='CurrencyService.GetCurrencies',
    index=0,
    containing_service=None,
    input_type=_CURRENCYTYPES,
    output_type=_CURRENCY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CURRENCYSERVICE)

DESCRIPTOR.services_by_name['CurrencyService'] = _CURRENCYSERVICE

# @@protoc_insertion_point(module_scope)
